# SPDX-FileCopyrightText: 2023 Christina Sørensen
# SPDX-FileContributor: Christina Sørensen
#
# SPDX-License-Identifier: AGPL-3.0-only

Set Shell fish
Type "fortune-kind"
Sleep 2s
Enter
Sleep 3s
Type "fortune-kind -m way"
Sleep 2s
Enter
Sleep 3s
Type "fortune-kind "
Sleep 2s
Enter
Sleep 3s
Type "fortune-kind"
Sleep 2s
Enter
Sleep 3s
Type "fortune-kind"
Sleep 2s
Enter
Sleep 3s
Type "fortune-kind"
Sleep 2s
Enter
Sleep 3s
Type "fortune-kind"
Sleep 2s
Enter
Sleep 3s

