on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build Nix targets
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5 # This action
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v6
      - name: Nix Flake Check
        run: nix flake check --all-systems
